### PR TITLE
Fixed issue with Unknown Host on curl command

### PR DESCRIPTION
**Pull request by InnerSpark**
Was getting an unknown host error from the curl command as the var was incorrect.

### CODE REVIEW

**Comment by jgillman** [comment]
Haha, I just spent 30 minutes debugging exactly this. I should have checked your PR first! It's the same fix I came to.

**Comment by tripflex** [comment]
@yoyostile you should really merge this PR, because had I not known to check github I would have ditched this one bc it doesn't work out of the box, just a simple case issue

**Comment by yoyostile** [comment]
Woah, sorry! Wasn't watching my own repo :(
I'll have a look!

**Comment by yoyostile** [comment]
Thanks a lot! My local Übersicht clone seems to be fixed :) Dunno why I commited the typo.

**Comment by tripflex** [comment]
@yoyostile no worries I know how it goes 😛  thanks for the quick response!

**Pull request merged**
